# Update required before running this file with docker-compose
# - <dnla uid>, User ID on host system, must have access write to download folder
# - <dnla guid>, Group ID on host system, must have access read or write to download folder,
#                depends on how access is organised, by group or user
# - <download folder on host>, Path to download folder on host system
# - <config folder on host>, Path to configuration folder on host system
---
services:
  # Uncomment to add jellyfin service
  # jellyfin:
  #   image: ghcr.io/linuxserver/jellyfin
  #   container_name: jellyfin
  #   environment:
  #     - PUID=<dnla uid>
  #     - PGID=<dnla guid>
  #     - TZ=Europe/London
  #   volumes:
  #     - <download folder on host>/Video:/Video
  #     - <download folder on host>/TVShows:/TVShows
  #     - <config folder on host>/jellyfin/config:/config
  #   ports:
  #     - 8096:8096
  #     - 8920:8920 
  #     - 7359:7359/udp 
  #     - 1900:1900/udp 
  #   restart: "unless-stopped"
  #   network_mode: "host"
  torrentino:
    # image: ghcr.io/adskyiproger/transmission-telegram-bot:latest
    image: tr
    container_name: transmission-telegram-bot
    # Transmission connection properties
    environment:
      # Transmission connection properties
      - TRANSMISSION_HOST=transmission
      - TRANSMISSION_PORT=9091
      - TRANSMISSION_USER=test
      - TRANSMISSION_PASSWORD=test
      - TOKEN=${TOKEN}
    depends_on:
      - "transmission"
    # Uncomment this line if you need to persist you configuration
    # in local folder or docker volume
    # volumes:
    # 1. Local folder example
    #   - ./config:/usr/src/app/config
    # 2. Docker volume example
    #   - config:/usr/src/app/config
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      # Uncomment to grant correct permissions
      # - PUID=<dnla uid>
      # - PGID=<dnla guid>
      - TZ=Europe/London
      - USER=test
      - PASS=test
    volumes:
      # Modify this section to add external volumes
      - downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

# Temporal volume for testing
# Please check: https://docs.docker.com/reference/compose-file/volumes/
volumes:
  downloads: {}
  config: {}