name: Run Linters and Checkers
# Test sync
on:
  push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - run: |
          pwd
          ls -la
          env
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          pwd
          ls -la
          env
    flake8:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.13

        - name: Install dependencies
          run: |
            pip install --user pipenv && \
            pipenv install && \
            pipenv install --dev
        - name: Flake8
          run: |
            pipenv run flake8

    mypy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.13
  
          - name: Install dependencies
            run: |
              pip install --user pipenv && \
              pipenv install && \
              pipenv install --dev
          - name: MyPy
            run: |
              pipenv run mypy .
